import Image from 'next/image';
import { SectionTitle } from '@/components/Section';
import { basicCommands, warps } from '@/lib/data';
const warpImages=['warp-crates','warp-coliseo','warp-end','warp-nether','warp-pets','warp-tienda','warp-restaurante','warp-misiones','warp-clanes','warp-portales','warp-casino','warp-gemas','warp-bosses','warp-pvp','warp-info'];
export default function Compendio(){return <main>
<section className="page-hero" style={{backgroundImage:"url('/images/hero/spawn-overview.webp')"}}><div><span className="badge">CONOCIMIENTO DEL SERVIDOR</span><h1>Compendio DriverCraft.</h1><p>Warps, comandos, sistemas, crates, economía, clanes, protecciones y consejos para entender todo el servidor.</p></div></section>
<section className="section"><SectionTitle eyebrow="Warps" title="Lugares importantes del mundo.">Estos son los puntos principales que podrás encontrar dentro de DriverCraft.</SectionTitle><div className="warp-grid content-block">{warps.map((w,i)=><div className="warp-card" key={w}><Image src={`/images/warps/${warpImages[i]}.webp`} alt={w} width={600} height={360}/><h3>{w}</h3></div>)}</div></section>
<section className="section"><SectionTitle eyebrow="Comandos" title="Herramientas del aventurero.">Los comandos básicos que todo jugador nuevo debería conocer.</SectionTitle><div className="command-grid content-block">{basicCommands.map(([cmd,desc])=><div className="command-card" key={cmd}><code>{cmd}</code><p>{desc}</p></div>)}</div></section>
<section className="section"><SectionTitle eyebrow="Sistemas" title="Todo lo que puedes hacer.">DriverCraft está diseñado para que siempre tengas algo nuevo por descubrir, aprender o reclamar.</SectionTitle><div className="two-col content-block"><article className="article-card"><h3>Progreso</h3><ul><li>Misiones con Nivel de Misión.</li><li>Daily diario.</li><li>Pets que suben de nivel.</li><li>Gemas que aparecen al derrotar criaturas.</li><li>Desafíos de bosses y PvP.</li></ul></article><article className="article-card"><h3>Economía y comunidad</h3><ul><li>/shop con objetos y spawners.</li><li>Casino para ganar o perder dinero.</li><li>Clanes para jugar en equipo.</li><li>Protecciones 16x16, 32x32 y 64x64 en /protecciones.</li><li>Crates con recompensas especiales.</li></ul></article></div></section>
</main>}
