import Image from 'next/image';
import { SectionTitle } from '@/components/Section';
import { bosses, gemLore } from '@/lib/data';
export default function Legado(){return <main>
<section className="page-hero" style={{backgroundImage:"url('/images/hero/spawn-night.webp')"}}><div><span className="badge">HISTORIA Y MISTERIO</span><h1>El Legado de los Reyes.</h1><p>Cuando los Reyes despertaron, su poder se dispersó por el mundo. Las criaturas absorbieron esa energía y algunas comenzaron a revelar Gemas.</p></div></section>
<section className="section story-section"><SectionTitle eyebrow="La historia" title="Antes de las Gemas, estuvieron los Reyes.">No eran simples criaturas. Eran fuerzas antiguas que dejaron una energía tan poderosa que todavía late dentro de algunos mobs del mundo.</SectionTitle><div className="story-timeline content-block">
  <article><span>01</span><h3>El despertar</h3><p>Los Reyes aparecieron en DriverCraft y su energía comenzó a recorrer la tierra, el Nether y los rincones más oscuros del mundo.</p></article>
  <article><span>02</span><h3>La dispersión</h3><p>Parte de ese poder se quebró en cristales. Así nacieron las Gemas: fragmentos antiguos con recompensas y misterio.</p></article>
  <article><span>03</span><h3>Las criaturas</h3><p>Con el paso de los ciclos, mobs y animales absorbieron esa energía. Por eso cualquiera podría revelar una Gema al morir.</p></article>
  <article><span>04</span><h3>Tu legado</h3><p>Cada Gema encontrada es una señal: el mundo todavía recuerda a los Reyes y espera aventureros capaces de enfrentarlos.</p></article>
</div></section>
<section className="section legacy"><SectionTitle eyebrow="Gemas" title="Cuatro rarezas. Una misma leyenda.">Mientras más rara es una Gema, más grande es su poder y mejores son sus recompensas.</SectionTitle><div className="gems-grid content-block">{gemLore.map((g)=><div className={`gem-card gem-${g.key}`} key={g.name}><div className="gem-orb"><Image src={`/images/gems/${g.key}.png`} alt={g.name} width={120} height={120}/></div><h3>{g.name}</h3><p><b>{g.line}</b></p><p>{g.story}</p></div>)}</div></section>
<section className="section"><SectionTitle eyebrow="Recompensas" title="Cada Gema puede cambiar tu aventura.">Bolsas de monedas, llaves, kits, manzanas encantadas, pets raros y recompensas únicas.</SectionTitle><div className="two-col content-block"><article className="article-card"><h3>Cómo se obtienen</h3><p>Al derrotar mobs o animales existe una posibilidad de que aparezca una Gema. Solo puede caer una por muerte y las más raras tienen prioridad en el orden de aparición.</p></article><article className="article-card"><h3>Compendio</h3><p>Usa <b>/gemas</b> dentro del servidor para abrir el Compendio de Gemas, ver lore, estadísticas, cómo obtenerlas y posibles recompensas.</p></article></div></section>
<section className="section boss-scrolls-section"><SectionTitle eyebrow="Los Reyes" title="El origen del poder. Los bosses de DriverCraft.">Rey Zombie, Rey Skeleton, Rey Enderman y Rey Blaze son los desafíos que mantienen vivo el misterio de las Gemas. Sus pergaminos nacen de las criaturas que aún cargan su energía.</SectionTitle><div className="boss-grid boss-scroll-grid">{bosses.map(b=><article className="boss-card boss-scroll-card" key={b.name} style={{'--boss-color':b.color} as any}><Image src={b.img} alt={b.name} width={600} height={500}/><div><h3>{b.name}</h3><p>{b.tone}</p><ul><li><b>Pergamino:</b> {b.scroll}</li><li><b>Se obtiene:</b> derrotando {b.mob}.</li><li><b>Elemento:</b> {b.element}</li></ul></div></article>)}</div></section>
</main>}
